import { Dua, IslamicEvent, Ziyarat } from './types';
import fetchedZiyarats from './data/ziyarats.json';
import fetchedDuas from './data/duas.json';
import fetchedNamaz from './data/namaz.json';
import fetchedSalatMasoomeen from './data/salat_masoomeen.json';
import fetchedSalawaat from './data/salawaat.json';

export const DUAS: Dua[] = fetchedDuas as Dua[];
export const NAMAZ: any[] = fetchedNamaz;
export const SALAT_MASOOMEEN: any[] = fetchedSalatMasoomeen;
export const SALAWAAT: any[] = fetchedSalawaat;
export const ZIYARATS: Ziyarat[] = fetchedZiyarats as Ziyarat[];


export const EVENTS: IslamicEvent[] = [

  // Muharram (1)
  {"hijriMonth":1,"hijriDay":1,"title":"Beginning of the Hijri Year","description":"The beginning of the Hijri year marks the start of a new Islamic calendar year.","type":"Event"},
  {"hijriMonth":1,"hijriDay":2,"title":"Arrival of Imam al-Hussain (as) to Karbala","description":"Imam Husayn arrives in Karbala on 2nd Muharram 61 A.H., where Umar bin Sad encamps opposite with 4000 soldiers. The Imam, invited by Iraqis, offers to return but Ibn Ziyad demands allegiance to Yazid and blocks water access. Negotiations fail; Ibn Ziyad orders unconditional surrender or attack. A security letter for Ummul Banin's sons is refused. Abbas secures a night's delay for prayers. The Imam addresses companions, urging them to leave for safety as martyrdom looms.","type":"Event"},
  {"hijriMonth":1,"hijriDay":7,"title":"Water supply to Imam Hussain's camp was stopped","description":"","type":"Event"},
  {"hijriMonth":1,"hijriDay":9,"title":"Shab-e-Ashura","description":"","type":"Event"},
  {"hijriMonth":1,"hijriDay":10,"title":"Martyrdom of Imam al-Hussain (as)","description":"Just over 50 years after Muhammad's death, Hussain, his grandson, opposed the corrupt Umayyad tyrant Yazid. Refusing to support evil, Hussain migrated from Medina to Mecca and toward Kufa but was blocked at Karbala by 30,000 troops. With 72 companions, deprived of water and outnumbered, they were killed for upholding principles. His sister Zainab condemned Yazid in his palace. Hussain's sacrifice inspired the Umayyad overthrow and millions worldwide who mourn him.","type":"Shahadat"},
  {"hijriMonth":1,"hijriDay":12,"title":"Ahlul Bayt (as) to Kufa","description":"The history of Imam Husayn's movement began in Rajab 60 A.H. with departure from Medina to Mecca, proceeding to Iraq in Zil-Hajj, and martyrdom in Muharram 61 A.H. Ahlul Bayt were taken as prisoners to Kufa, then to Damascus per Yazid's orders, staying an unknown period before returning to Medina within a year, possibly via Karbala en route to Syria but without reliable evidence. Myths of returning to Karbala on 20th Safar or Arba'in, or meetings with Jabir and Atiyya, are debunked as unhistorical, including Sayyid bin Tawus's account. Historical research is urged over blind acceptance, with infallibility only for the Prophet, Fatima, and Imams.","type":"Event"},
  {"hijriMonth":1,"hijriDay":12,"title":"Soyem Shuhada-e-Karbala (AS)","description":"","type":"Event"},
  {"hijriMonth":1,"hijriDay":13,"title":"Burial of the Martyrs of Karbala","description":"After the Battle of Karbala, Imam Zainul Aabidin succeeded as the fourth Imam while unconscious with fever; Lady Zainab consulted him, affirming his authority, and he ordered the family to leave burning tents to survive and spread the truth of the atrocities. She searched for and found missing children dead, including Sukaina near a headless body, hearing Husayn's voice. Martyrs' bodies were left, trampled barbarically by horses under Umar bin Sa’d's orders, with items pillaged. Per Shiite belief, Zainul Aabidin miraculously buried the bodies with Banu Asad's help, later rejoining heads.","type":"Event"},
  {"hijriMonth":1,"hijriDay":19,"title":"Departure of Ahlul al-Bayt (as) from Kufa to Sham","description":"After stirring remorse in Kufa, the captives, including Bibi Zainab and Imam Zain ul 'Abideen, secretly departed at night for a grueling 20-day journey to Damascus through deserts, enduring heat, floggings, and child deaths. In Yazid's court, Bibi Zainab and the Imam boldly confronted his arrogance, reciting Quran and affirming Husayn's victory. Imprisoned in a dungeon, young Bibi Sakina died of grief; Yazid released them after her death, allowing mourning majlises in Damascus that spread sympathy for Ahlul Bait.","type":"Event"},
  {"hijriMonth":1,"hijriDay":23,"title":"Bombing of the al-Askari shrine","description":"The Al-Askari Shrine, a Twelver Shi'ite mosque and mausoleum in Samarra, Iraq, built in 944 CE, is a key Shia site housing the tombs of Imams Ali al-Hadi (as) and Hasan al-Askari (as), plus Hakima Khatun and Narjis Khatun. Its dome was bombed in 2006 by Sunni extremists, minarets in June 2007, and clock tower in July 2007, sparking Shia anger and the Iraqi Civil War. Repaired, it reopened in April 2009 and lies within the Samarra UNESCO World Heritage Site listed in 2007. Adjacent is the Serdab marking the Twelfth Imam's Minor Occultation.","type":"Event"},
  {"hijriMonth":1,"hijriDay":25,"title":"Martyrdom of Imam Zayn al-Abidin (as)","description":"Imam Zayn al-Abidin weakened from worship and Karbala memories, gaining popularity that alarmed Umayyad ruler al-Walid b. 'Abd al-Malik, who poisoned him. Suffering severe pain, he praised Allah for martyrdom and designated his son Mohammed al-Baqir as successor, entrusting him with Imamate, commandments, and inheritances. Al-Baqir prepared and buried him in al-Baqi Cemetery beside Imam al-Hasan amid massive mourning in Medina.","type":"Shahadat"},

  // Safar (2)
  {"hijriMonth":2,"hijriDay":1,"title":"Entry of Ahlul Bayt (as) into Sham","description":"The head of Imam Husayn (a.s.) arrived in Damascus on the 1st of Safar, celebrated by Bani Umayyah as a day of rejoicing but mourned by believers. Yazid mocked the head, poking its teeth and reciting vengeful poems about Badr. The captives, including Ahlul Bayt, entered humiliated; Zainab and Zainul Abedeen delivered powerful sermons rebuking Yazid with Quranic verses. Interactions, dreams, and lamentations ensued, leading to Yazid's feigned regret and the captives' eventual release after 66 days.\n\n","type":"Event"},
  {"hijriMonth":2,"hijriDay":1,"title":"Battle of Siffin","description":"The Battle of Siffin in 657 pitted Ali against Muawiya's Syrian army on the Euphrates. Ali sought unity and peace, but Muawiya refused, leading to skirmishes and intense fighting. Ammar ibn Yasir was martyred, fulfilling a prophecy. Malik ibn Ashter's night assault nearly won, but traitors in Ali's ranks, bribed by Muawiya, halted the battle by raising Qur'ans on lances, forcing arbitration. Abu Musa deposed both leaders, but Amr bin Aas appointed Muawiya, sparking Khawarij rebellion against Ali.","type":"Event"},
  {"hijriMonth":2,"hijriDay":5,"title":"Martyrdom of Ruqayya bint Imam al-Hussain (as)","description":"The martyrdom of Ruqayya bint Al-Ḥusayn, a four-year-old daughter of Imam Husayn, is described in Kamile Bahai from Kitab al Hawiyah. The family had concealed the fathers' deaths from children, claiming they were on a journey. At Yazid's house, Ruqayya awoke distressed from a dream about her father. Upon Yazid's order, Imam Husayn's head was brought to her. Recognizing it, she lamented poetically, kissed it, and died from grief in Damascus, prompting widespread mourning. Yazid then ordered the heads hanged on city doors.","type":"Shahadat"},
  {"hijriMonth":2,"hijriDay":7,"title":"Wiladat: Imam Musa al-Kadh'im (AS)","description":"","type":"Wiladat"},
  {"hijriMonth":2,"hijriDay":9,"title":"Battle of Nahrawan","description":"In the Battle of Siffin, Mu’awiya's trick of raising Qur’ans on spears halted the fight, leading to arbitration. Amr ibn ‘As tricked Abu Musa Ash’ari into deposing Ali, then reinstated Mu’awiya as caliph. This sparked the Kharijites' rebellion against Ali for accepting arbitration. They withdrew to Harura, pledged to Abdullah ibn Wahab, moved to Nahrwan, and began killings. Ali confronted them, some repented, but battle ensued at Nahrwan, where Ali prevailed, though it demoralized his forces. Kharijites later persisted, evolving into the Ibadi sect in places like Oman and Algeria.","type":"Event"},
  {"hijriMonth":2,"hijriDay":17,"title":"Martyrdom of Imam Ali al-Rida (as)","description":"Imam Ali al-Ridha, the Eighth Imam, was born in 148 Hijri in Madina and succeeded his father Imam Musa al-Kazim at age 35 in 183 Hijri. Amid Abbasid persecution, he was summoned by Caliph Mamun to Merv in 200 Hijri, appointed heir-apparent to gain Persian support, and led a simple, pious life while establishing Majalis for Karbala commemorations. He died in Tus in 203 Hijri, poisoned by Mamun's orders, and was buried there.","type":"Shahadat"},
  {"hijriMonth":2,"hijriDay":20,"title":"Arba'een Imam al-Hussain (as)","description":"The Day of Arbaeen, marking 40 days after Ashura and the martyrdom of Hussain ibn Ali in the Battle of Karbala, commemorates his stand for social justice against corrupt ruler Yazid. Hussain refused to legitimize Yazid's regime and was killed with his companions. His family, imprisoned and paraded, later exposed Yazid through speeches and spread his message. Today, millions worldwide join marches and an 80km pilgrimage from Najaf to Karbala, the largest peaceful gathering, with volunteers providing aid despite threats.","type":"Event"},
  {"hijriMonth":2,"hijriDay":24,"title":"Wafat: Bibi Zainab (SA) (some traditions)","description":"","type":"Shahadat"},
  {"hijriMonth":2,"hijriDay":28,"title":"Death of Prophet Muhammad (pbuh)","description":"Muhammad, the Prophet of Islam, achieved his divine aims in 23 years, including eradicating idolatry and establishing a just state. Intimations of his death came via Surah Nasr and speeches at Arafat and Ghadeer-Khumm. His fatal illness began on 20 Safar 11 AH after visiting Al-Baqi cemetery, marked by headaches and fever. He led his last prayer on 26 Safar, praising Abu Bakr and advising the umma. He died on 1 Rabi al-Awwal, aged 63, buried by Ali and family while companions elected Abu Bakr caliph.","type":"Shahadat"},
  {"hijriMonth":2,"hijriDay":28,"title":"Martyrdom of Imam al-Hasan (as)","description":"Mu’awiya, having built a strong base in Syria, transformed the caliphate into a hereditary monarchy by appointing his son Yazid as successor, breaching his pledge to Imam Hasan ('a). Anticipating opposition, Mu’awiya orchestrated Hasan's poisoning through his wife Jo’dah bint Ash'ath, promising her 100,000 dirhams and marriage to Yazid, but later reneged on the marriage. After Hasan's death in 669, ‘Aisha, mounted on a mule with Umayyads, prevented his burial beside Prophet Muhammad (S) in Medina, leading to his interment in Jannat-ul-Baqi; Ibn Abbas rebuked her actions.","type":"Shahadat"},
  {"hijriMonth":2,"hijriDay":29,"title":"Martyrdom Of Imam Ali Raza (AS)","description":"","type":"Shahadat"},

  // Rabi al-Awwal (3)
  {"hijriMonth":3,"hijriDay":1,"title":"Hijrat-e-Madina / Shab-e-Hijrat","description":"","type":"Event"},
  {"hijriMonth":3,"hijriDay":5,"title":"Death of Sukayna bint Imam al-Hussain (as)","description":"Sukaynah Bint al-Husayn, daughter of Imam al-Husayn and al-Rabab, was commonly known as Sukaynah, though also called Aminah or Umaymah. She married her cousin 'Abdullah Ibn al-Hasan, martyred in Karbala, and later Mus'ab Ibn al-Zubayr (daughter Rabab born), 'Abdullah Ibn 'Uthman (sons Hakim and 'Uthman), and Zayd Ibn 'Amr. After Karbala captivity to Damascus and Medina, she died in Medina on 5 Rabi' al-Awwal 117 AH under Khalid Ibn 'Abd al-Malik, with burial delayed due to heat. Some claim death in Mecca 126 AH; Damascus shrine is for another Sukaynah. Last marriage questioned by historians.","type":"Shahadat"},
  {"hijriMonth":3,"hijriDay":8,"title":"Martyrdom of Imam al-Askari (as)","description":"Imam al-Hasan al-‘Askari, the eleventh Imam, was born in 232/846 in Medina to mother Susan or Salil. He lived 29 years, divided into periods in Medina and Samarra, with six years of Imamate under Abbasid oppression, including three in prison. Known for eloquence, Qur’anic interpretation, and scholarly influence, he guided Shi’as amid restrictions preparing for his son’s occultation. Martyred by poison in 260/874, his successor, Imam al-Mahdi, was revealed through miraculous signs to devoted followers.","type":"Shahadat"},
  {"hijriMonth":3,"hijriDay":9,"title":"Eid al-Zahra (as)","description":"Eid e Zehra on the 9th of Rabi'al Awwal is a joyous day for AhlulBayt followers, known as the Greatest Eid and second Eid e Ghadeer. It follows 80 days of mourning for Imam Husain's martyrdom in Karbala and deaths of the Prophet, 2nd, 4th, 8th, and 11th Imams. The day marks the start of the 12th Imam's Imamate during his Occultation. It emphasizes Tawalla (love for AhlulBayt) and Tabarra (hatred for their enemies), as per hadiths and Quran.","type":"Eid"},
  {"hijriMonth":3,"hijriDay":15,"title":"Building of the first mosque in Quba","description":"","type":"Event"},
  {"hijriMonth":3,"hijriDay":17,"title":"Wiladat Of Prophet Muhammad (pbuh)","description":"Muhammad was born posthumously in 570 CE in Makkah to Amina after Abdullah's death, inheriting property like camels and sheep, proving prophets can bequeath to children—contrasting later seizure of Fadak from Fatima. Sent to desert nurse Halima for four years, he returned at five; mother died at six, grandfather Abdul Muttalib at eight, who entrusted him to uncle Abu Talib, new Banu Hashim leader. Abu Talib raised him lovingly; at twelve, Muhammad traveled to Syria, earning titles Al-Amin and Sadiq for trustworthiness. At twenty, he joined war without fighting and the League of the Virtuous against exploitation.","type":"Wiladat"},
  {"hijriMonth":3,"hijriDay":17,"title":"Wiladat Of Imam Ja'far al-Sadiq (as)","description":"Ja'far ibn Muhammad al-Sadiq, the sixth Shi’a Imam, born in 83 or 86 A.H., was renowned for his scholarship, piety, and founding Ja’fari jurisprudence. His Imamate (114-148 A.H.) spanned seven caliphs and the Umayyad-Abbasid transition, allowing him to train thousands of students, including Abu-Hanifah, in Islamic sciences. He demonstrated vast knowledge in debates and texts like Tawhid al-Mufaddal, supported Shi’a uprisings such as Zayd’s, confronted tyrants non-violently, and was martyred by poison at age 65 in 148 A.H.","type":"Wiladat"},
  {"hijriMonth":3,"hijriDay":26,"title":"Treaty of Peace between Imam al-Hasan (as) and Muawiyah","description":"Mu'awiya sent al-Hasan a blank stamped page to stipulate peace treaty conditions, which al-Hasan filled with terms beneficial to him, his family, and Shi'a. Historians provide scattered details, with one claiming a complete text refuted by others. Key items include: authority handover conditional on following Quran, Sunna, and righteous Caliphs; succession to al-Hasan then al-Husayn; ceasing curses against Ali; financial provisions like treasury exclusion, annual payments, and martyr compensations; security for all, especially Ali's companions, without pursuit or harm. Mu'awiya confirmed with writing, oath, and witnesses in mid-Jumada al-Ula, 41 AH.","type":"Event"},

  // Rabi al-Thani (4)
  {"hijriMonth":4,"hijriDay":8,"title":"Martyrdom of Fatima al-Zahra (as)","description":"After the Prophet's death, a group of up to 4000 men, led by Umar ibn Khattab, demanded Ali ibn Abi-Talib's allegiance to Abu Bakr at Fatima tuz Zahra's door. Ali, preparing the Qur'an, refused. They threatened to burn the house, set fire to the door, kicked it in, injuring Fatima—breaking her rib and causing miscarriage of Al-Muhassin. On her deathbed, Fatima requested a secret night burial attended by few loyal companions like Ali, al-Hassan, al-Husayn, Ammar bin Yasir, and Salman al-Muhammadi. Her grave's location remains unknown. Ali, who lifted Khaybar's gates effortlessly, wept unable to lift her body.","type":"Shahadat"},
  {"hijriMonth":4,"hijriDay":10,"title":"Wiladat Of Imam al-Askari (as)","description":"Imam Hasan al-Askari, the Eleventh Imam, was born in 232 Hijri in Madina and died in 260 Hijri in Samarra at age 28, after a 6-year Imamate under house arrest. Titled Askari for living in a garrison town, he taught Quran, wrote a Tafseer, and performed miracles like exposing a priest's rain trick and praying for rain. He married Nargis Khatoon, a Rum princess who converted via dreams, mother to his son Muhammad. Despite sufferings, he educated students and converted atheists. Poisoned by Caliph al-Mu’tamid, his 5-year-old son led his funeral prayer before disappearing. Buried with his father in Samarra.","type":"Wiladat"},
  {"hijriMonth":4,"hijriDay":10,"title":"Death of Fatima al-Masuma (as)","description":"Lady Fatima Masuma (A), daughter of Imam Musa al-Kazim (A) and Najmah Khatun, was born on 1st Dhul Qa`dah 173 A.H. in Medina and died in Qum in 201 A.H. at age 28. Imams foretold her birth and burial in Qum over 45 years prior, promising paradise for her visitors and intercession for Shia. Known as Masuma and Karimat Ahl al-Bayt, she remained unmarried due to lack of suitable spouses amid persecution. A knowledgeable narrator of traditions, she was highly influenced by her father and brother, Imam Ali al-Rida (A).","type":"Shahadat"},
  {"hijriMonth":4,"hijriDay":14,"title":"Uprising of al-Mukhtar al-Thaqafi to Avenge Imam al-Hussain (as)","description":"The chapter examines Shi’ism's origins in political caliphal struggles, involving oligarchic timocracy and marginalized resistance, intertwined with religion unlike Western church-state separation. It details early divisions after Imams ‘Ali, Hasan, and Husayn, focusing on Mukhtar al-Thaqafi's 685-686 Kufah insurrection as enlightened messianic activist, avenging Husayn's death on behalf of Muhammad Ibn al-Hanafiyyah as Mahdi. Shi’ism is a metaphysical restoration of Prophethood through Imams' wilayah, not mere politics or founded by figures like Ibn Saba’.","type":"Event"},

  // Jumada al-Awwal (5)
  {"hijriMonth":5,"hijriDay":5,"title":"Wiladat Of Zainab (as)","description":"Lady Zainab (as) was the third child of Lady Fatima az-Zahra (sa), born in 5 A.H. after Imam Husayn (as), refuting claims she followed a miscarriage of Mohsin, which historians like Bint Ash-Shati use to downplay the attack on Fatima's house. Named \"Zainab\" by the Prophet (S), meaning \"embellishment of her father,\" or via Gabriel. Her life involved noble traits amid tragedies: deaths of grandfather and mother, father's confinement, his martyrdom, battles, Hasan's poisoning, Karbala massacre, captivity to Syria, return to Medina, and exile to Egypt, where her tomb is visited (though most believe it's in Syria).","type":"Wiladat"},
  {"hijriMonth":5,"hijriDay":10,"title":"Battle of the Camel","description":"The Battle of Basra, or Battle of the Camel, marked the Second Civil War in Islam after Uthman's assassination and Ali's accession as caliph. Ayesha, Talha, and Zubayr, using vengeance for Uthman as pretext for their ambitions, raised a 3000-strong army in Mecca, captured Basra, killed 600 Muslims, and seized the treasury. Ali, after failed peace efforts and mustering 700 volunteers plus Kufan reinforcements, confronted them. Negotiations failed; Zubayr deserted and was killed, Talha died in battle, and Ayesha's camel became the focal point until slain, leading to rebel defeat. Ali showed mercy, pardoned leaders including Ayesha, and reunited the umma.","type":"Event"},
  {"hijriMonth":5,"hijriDay":13,"title":"Martyrdom of Fatimah al-Zahra (as)","description":"After the Prophet's death, a group of up to 4000 men, led by Umar ibn Khattab, demanded Ali ibn Abi-Talib's allegiance to Abu Bakr at Fatima tuz Zahra's door. Ali, preparing the Qur'an, refused. They threatened to burn the house, set fire to the door, kicked it in, injuring Fatima—breaking her rib and causing miscarriage of Al-Muhassin. On her deathbed, Fatima requested a secret night burial attended by few loyal companions like Ali, al-Hassan, al-Husayn, Ammar bin Yasir, and Salman al-Muhammadi. Her grave's location remains unknown. Ali, who lifted Khaybar's gates effortlessly, wept unable to lift her body.","type":"Shahadat"},

  // Jumada al-Thani (6)
  {"hijriMonth":6,"hijriDay":3,"title":"Martyrdom of Fatimah al-Zahra (as)","description":"After the Prophet's death, a group of up to 4000 men, led by Umar ibn Khattab, demanded Ali ibn Abi-Talib's allegiance to Abu Bakr at Fatima tuz Zahra's door. Ali, preparing the Qur'an, refused. They threatened to burn the house, set fire to the door, kicked it in, injuring Fatima—breaking her rib and causing miscarriage of Al-Muhassin. On her deathbed, Fatima requested a secret night burial attended by few loyal companions like Ali, al-Hassan, al-Husayn, Ammar bin Yasir, and Salman al-Muhammadi. Her grave's location remains unknown. Ali, who lifted Khaybar's gates effortlessly, wept unable to lift her body.","type":"Shahadat"},
  {"hijriMonth":6,"hijriDay":13,"title":"Death of Umm al-Banin (as)","description":"Umm-ul-Banin, originally Fatima daughter of Hizam from a celebrated Arab family known for heroism and nobility, married Imam Ali after Fatima's death, on the advice of Aqil to bear a courageous son to support al-Husayn. She exceptionally cared for al-Hasan and al-Husayn, loving them more than her own four sons—al-Abbas, Abdullah, Ja’far, and Uthman—out of religious duty per the Qur’an. Revered by the Ahlul Bayt and Muslims for her loyalty and sacrifice in Karbala, she never remarried after Ali's death.","type":"Shahadat"},
  {"hijriMonth":6,"hijriDay":19,"title":"Marriage of Abdullah and Aminah (The parents of the Prophet)","description":"The narration describes the Prophet Muhammad's pure lineage from noble loins and wombs, guiding others, with his name derived from Allah's name Mahmoud, affirming his mother's noble character. In Mecca, his father Abdullah, son of Abdul Muttalib, was known for the radiating light on his face, attracting many women for marriage. A story recounts Aminah's marriage to him, amid Jewish scholars in Sham disturbed by the final Messenger's arrival in Mecca, unable to alter God's decree.","type":"Event"},
  {"hijriMonth":6,"hijriDay":20,"title":"Wilādat Fatimah al-Zahra (as)","description":"Disagreement exists on Fatima az-Zahra's birth: Shiite traditions affirm five years after revelation, on 20th Jamadi al-Thani, supported by Imams and scholars like Kulayni and Mufeed. Sunni views place it five years before, during Kaaba construction. Post-revelation birth is deemed true, with false claims motivated by denying paradise-related conception and alleging her unattractiveness. Birth involved angelic midwives like Eve and Maryam assisting Khadija, who personally nursed her.","type":"Event"},
  {"hijriMonth":6,"hijriDay":21,"title":"Death of Umm Kulthum (as) (dauther of Imam Ali)","description":"Umm Kulthum, daughter of Ali Ibn Abi Talib and Fatimah al-Zahra', was born in 6 A.H. Scholars confirm her as one of Fatimah's daughters, distinct from others with similar names. She married Umar under duress, bearing Zayd and Ruqayyah, then wed Awn Ibn Ja'far after Umar's death. She died in Medina before Karbala', buried with son Zayd during al-Hasan and al-Husayn's lifetime. Known for piety, eloquence, and narrating traditions amid family tragedies.","type":"Shahadat"},

  // Rajab (7)
  {"hijriMonth":7,"hijriDay":1,"title":"Wiladat Of Imam Muhammad al-Baqir (as)","description":"The Fifth Imam, Muhammad Ibn ‘Ali al-Baqir (as), born in Madina on 1st Rajab 57 Hijri and died on 7th Zilhijja 114 Hijri at age 57, led a 19-year Imamate. Fulfilling a prophecy, he was recognized by Jabir ibn Abdullah. He opened schools teaching Qur’an and Hadith, earning the title Baqir for his knowledge. He advised on Islamic currency, regained Fadak under Umer Ibn Abdul Aziz, and faced harassment from Hisham, demonstrating archery skills. His schools trained 25,000 students and produced 400 Hadith books. Poisoned by Ummayads, he was succeeded by Ja’far Sadiq (as).","type":"Wiladat"},
  {"hijriMonth":7,"hijriDay":2,"title":"Wiladat Of Imam Ali al-Hadi (as)","description":"Imam al-Hadi (a.s.), born in 212 AH in Medina to Imam al-Jawad (a.s.) and a bondmaid mother, inherited a noble lineage from prophethood and Imamate. Named Ali with epithets like al-Naqi and al-Hadi, he displayed early genius, piety, and knowledge, astonishing teachers and earning reverence from Muslims, Alawids, and even Christians. Raised in a virtuous family, he embodied high morals, asceticism, and jurisprudence, as praised by historians for his honor, wisdom, and infallibility.","type":"Wiladat"},
  {"hijriMonth":7,"hijriDay":3,"title":"Martyrdom of Imam Ali al-Hadi (as)","description":"Imam al-Hadi (a.s.), born in 212 AH in Medina to Imam al-Jawad (a.s.) and a bondmaid mother, inherited a noble lineage from prophethood and Imamate. Named Ali with epithets like al-Naqi and al-Hadi, he displayed early genius, piety, and knowledge, astonishing teachers and earning reverence from Muslims, Alawids, and even Christians. Raised in a virtuous family, he embodied high morals, asceticism, and jurisprudence, as praised by historians for his honor, wisdom, and infallibility.","type":"Shahadat"},
  {"hijriMonth":7,"hijriDay":10,"title":"Wiladat Of Imam Muhammad al-Jawad (as)","description":"Imam Muhammad al-Jawad (a.s.), the ninth Shia Imam, descended from the noble Prophet's family through his father, Imam Ali ar-Ridha (a.s.), and a virtuous bondmaid mother whose name historians dispute (e.g., al-Khayzuran or Sukaynah). Born on 19 Ramadan 195 AH in Medina, he was raised in the house of imamate, displaying early intelligence and genius that astonished scholars. Epithets like al-Jawad (generous) and al-Taqiy (pious) reflect his virtues, praised by his father and contemporaries for knowledge, piety, and generosity.","type":"Wiladat"},
  {"hijriMonth":7,"hijriDay":12,"title":"Imam Ali (as) Establishes Kufa as Seat of Caliphate","description":"In Rajab 36 A.H. (January 657), Ali transferred the Islamic capital from Medina to Kufa after victory in the Battle of the Camel, appointing Abdullah ibn Abbas as Basra's governor. Reasons included rewarding Kufa's support, protecting Medina from civil strife and desecration, its central administrative position, and monitoring Muawiya. Additional factors: preserving Medina's pure Islamic culture from alien influences, vice, and language corruption; presenting true egalitarian Islam; and ensuring security for holy cities like Medina and Makkah.","type":"Event"},
  {"hijriMonth":7,"hijriDay":13,"title":"Wiladat Of Imam Ali (as)","description":"Ali ibn Abi Talib was born on the 13th of Rajab in the 30th year of the Elephant (600 AD) inside the Kaaba in Makkah, to parents Abu Talib and Fatima bint Asad of the Hashim clan. His cousin Muhammad, aged 30, greeted and dedicated the infant to Allah, unlike other Arab children dedicated to idols. Ali never worshipped idols and was adopted by Muhammad at age five to be groomed for his destiny. Historians affirm his unique birth and life's full historical visibility, linking him inseparably to Islam's rise.","type":"Wiladat"},
  {"hijriMonth":7,"hijriDay":14,"title":"Wafat: Bibi Zainab (SA) (some traditions)","description":"","type":"Shahadat"},
  {"hijriMonth":7,"hijriDay":15,"title":"Change of Qibla to the Kaaba","description":"After the Prophet's migration to Medina, the qiblah changed from Bayt al-Maqdis to the Ka'bah in the 17th month, following divine command in Quran 2:144, amid Jewish opposition and mockery. This shift tested true believers (Quran 2:143), attracted Arabs by honoring the Ka'bah built by Ibrahim, and distanced Muslims from obstructive Jews, similar to replacing Ashura fasting with Ramadan. During noon prayer, Jibreel turned the Prophet precisely toward the Ka'bah, aligning exactly with modern coordinates—a scientific miracle without instruments.","type":"Event"},
  {"hijriMonth":7,"hijriDay":15,"title":"Death of Zainab (as)","description":"Historians debate Bibi Zaynab's death and burial: some say Medina's Jannatul Baqih, others Cairo on 14th Rajab 62 AH at Muslima Ibn Makhlid's house, or Damascus/Rawiya after illness en route to her husband. Overwhelmed by Karbala's tragedies—thirst, killings, captivity—she died heartbroken on 15th Rajab 62 AH, 17 months later. Reflections emphasize her steadfastness, critique insincere mourning in majalis, urge sincerity, lessons against tyranny, and Quranic insights on life's recorded deeds for judgment.","type":"Shahadat"},
  {"hijriMonth":7,"hijriDay":20,"title":"Wiladat: Hazrat Sakina (SA)","description":"","type":"Wiladat"},
  {"hijriMonth":7,"hijriDay":22,"title":"Nazr-e-Imam Jafar-us-Sadiq (AS) (Koonday)","description":"","type":"Event"},
  {"hijriMonth":7,"hijriDay":24,"title":"Battle of Khaybar","description":"The Battle of Khaybar occurred in the 7th year of Hijrah against the Jews who had amassed 10,000 warriors to attack Medina. Muslims, initially defeated over three days by warriors Marhab and Harith despite attacks led by Abu Bakr and Umar, faced difficulties as the Prophet suffered a migraine and Ali had sore eyes. The Prophet then cured Ali's eyes with saliva, gave him the flag, and Ali killed Marhab and Harith, uprooted the fort's gate as a shield, and conquered Khaybar with divine help.","type":"Event"},
  {"hijriMonth":7,"hijriDay":25,"title":"Martyrdom of Imam Musa al-Khadim (as)","description":"Imam Musa Al-Kadhim, born in 128 A.H. in Abwa’, son of Imam Ja’far Sadiq, served as the seventh Imam for 35 years until his martyrdom by poisoning in 183 A.H. in Baghdad’s prison at age 55, buried in Al-Kadhimiyn. Despite caliphal surveillance and imprisonment, he focused on worship, scholarship, teaching, and guiding followers. Traditions from Imam Sadiq confirm his imamate. Renowned for piety, knowledge, generosity, and tolerance, he aided the poor anonymously and exemplified forgiveness.","type":"Shahadat"},
  {"hijriMonth":7,"hijriDay":26,"title":"Death of Abu Talib (the prophets uncle)","description":"The death of Abu Talib marked a painful loss for Prophet Muhammad and the Muslims after the end of the Quraysh blockade, depriving them of a key protector who had safeguarded the Prophet since childhood. Abu Talib's love stemmed from kinship and faith in Muhammad's prophethood, evident in acts like praying for rain, accompanying him to Syria, and defending him against assassination plots by Quraysh chiefs. His sacrifices, driven by belief in Islam, included risking his life and status; Imams later affirmed his sincere faith.","type":"Shahadat"},
  {"hijriMonth":7,"hijriDay":27,"title":"Prophethood of Prophet Muhammad (s)","description":"Prophethood began with Adam and culminated in Muhammad as the final prophet, delivering the message of monotheism and submission to God. Muhammad's life involved early hardships, revelation in the Cave of Hira, secret and open propagation of Islam in Mecca amid persecution, migration to Medina (Hijra), key battles like Badr, Uhud, Ahzab, and Khaybar, the peaceful conquest of Mecca, and the Farewell Pilgrimage where he appointed Ali as successor at Ghadir Khumm. Preparations for Imam Al-Mahdi's future arrival emphasize justice and guidance from the Ahl al-Bayt.","type":"Event"},
  {"hijriMonth":7,"hijriDay":28,"title":"Imam Hussain (AS) started his journey from Medina to Mecca","description":"","type":"Event"},

  // Sha'ban (8)
  {"hijriMonth":8,"hijriDay":1,"title":"Wiladat: Bibi Zainab (SA) (some traditions)","description":"","type":"Wiladat"},
  {"hijriMonth":8,"hijriDay":3,"title":"Wiladat Of Imam al-Hussain (as)","description":"Husayn, son of Ali and Fatimah, was born in the fourth year of Hijrah as the third Shi'i Imam, with a miraculous six-month gestation like Jesus. Prophets from Adam to Jesus foretold his Karbala martyrdom, evoking universal grief, including from angels and Zachariah. Gabriel announced it to Muhammad, who nursed the infant Husayn, ensuring Imamate continuity. Stories depict miracles, esoteric knowledge, and virtues like courage, generosity, and piety, linking him to sacred history from Abel to the Mahdi.","type":"Wiladat"},
  {"hijriMonth":8,"hijriDay":4,"title":"Wiladat Of al-Abbas (as)","description":"Al-Abbas, born on 4th Shaban AH 26 to Umm-ul-Banin, was the first child celebrated by Imam Ali with Islamic newborn ceremonies including azan, iqama, hair shaving, alms, and sacrifice. Named al-Abbas (meaning courageous lion) and nicknamed Abu’l-Fadhl (father of virtue), he received protective verses from his mother. Imam Ali predicted his future martyrdom. Raised by faithful parents and adhering to Imams Ali, al-Hasan, and al-Husayn, al-Abbas embodied virtues, knowledge, and loyalty.","type":"Wiladat"},
  {"hijriMonth":8,"hijriDay":5,"title":"Wiladat Of Imam Ali Zayn al-Abidin (as)","description":"Imam Zayn al-‘Abidin, born in 38 A.H. possibly in Kufa, was named by Prophet Muhammad as ‘Ali b. al-Husayn, surnamed Zayn al-‘Abidin, foretold ten years prior. His birth rites included azan, iqama, and aqiqa. Nicknames like Sayyid al-‘Abidin, al-Sajjad, and Dhu’ al-Thafanat reflect his piety and worship. His mother died in childbirth; a nursemaid raised him. He was thin, weak, solemn, with a ring inscribed “My success is not but by Allah.”","type":"Wiladat"},
  {"hijriMonth":8,"hijriDay":7,"title":"Wiladat: Hazrat Qasim Ibne Hasan (AS)","description":"","type":"Wiladat"},
  {"hijriMonth":8,"hijriDay":11,"title":"Wiladat Of Ali al-Akbar (as)","description":"Ali al-Akbar, eldest son of Husayn ibn Ali (third Shia imam and grandson of Prophet Muhammad), was born to Layla from the Banu Thaqif tribe, with maternal ties to the Banu Umayya through her grandmother Maymuna. Praised by Caliph Mu'awiya for embodying traits of Banu Hashim, Umayya, and Thaqif, he strikingly resembled Muhammad in appearance and manners, earning the epithet Shabih-e Payghambar. His age at the Battle of Karbala (680 CE) is disputed (18-25 years), with 25 most likely, as he was older than survivor Ali Zayn al-Abidin (likely 23).","type":"Wiladat"},
  {"hijriMonth":8,"hijriDay":15,"title":"Wiladat Of Imam al-Mahdi (as)","description":"On July 29, AD 869, Imam Mahdi was born amid divine light, testifying to God's oneness, prophets' prophethood, and ancestors' Imamate while bowing toward the qiblah. Angels descended to congratulate Imam Hasan, and the infant recited holy books of past prophets. Archangel Rizwan washed him, Imam Hasan transferred wilayah and recited adhan. Green birds (angels led by Gabriel) took the newborn to God's Throne, where He affirmed Mahdi's role as the last proof, promising justice through him.","type":"Wiladat"},
  {"hijriMonth":8,"hijriDay":15,"title":"Beginning of the Major Occultation","description":"The Major Occultation began in 328 A.H. after Ali bin Muhammad Samari's death, with deputyship passing to great jurists; the Imam communicated via letters and audiences to Shia scholars like Shaykh Mufeed. Hypocrites like Ahmad bin Hilal, Hasan Sharii, Husain bin Mansur al Hallaj, and Muhammad bin Ali Shalmaghani falsely claimed deputyship due to jealousy or greed, promoting deviations and facing curses or execution. H","type":"Event"},

  // Ramadan (9)
  {"hijriMonth":9,"hijriDay":1,"title":"Start of Ramadan","description":"","type":"Event"},
  {"hijriMonth":9,"hijriDay":10,"title":"Death of Khadijah al-Kubra (as)","description":"Khadīja bt. Khuwaylid (a), known as Khadīja al-Kubrā (a) and Umm al-Mu'minīn, was the first wife of Prophet Muhammad (s) and mother of Lady Fatima (a). She married him 15 years before Bi'tha (595 CE) and was the first woman to convert to Islam, dedicating her wealth to its expansion. The Prophet (s) did not marry another during her lifetime and always praised her. She died in 4 BH/619 in Mecca and is buried in al-Ma'lat Cemetery in Mount al-Hajun.","type":"Shahadat"},
  {"hijriMonth":9,"hijriDay":14,"title":"Death of Mukhtar al-Thaqafi (ra)","description":"The article defends Mukhtar al-Thaqafi's character against controversies, portraying him as a loyal Shi'a revolutionary who avenged Imam Husayn's killers, uplifted the underprivileged, and promoted social equality in seventh-century Iraq. Accusations of heresy, founding sects like the Kaysaniyyah, and falsely naming Muhammad ibn al-Hanafiyyah as Mahdi are dismissed as Umayyad propaganda. Mukhtar's bravery, honor, and generosity are highlighted, emphasizing his focus on justice over doctrinal innovation.","type":"Shahadat"},
  {"hijriMonth":9,"hijriDay":15,"title":"Wiladat Of Imam al-Hassan (as)","description":"Fatima az-Zahra gave birth to Imam Hasan on Ramadhan 15, 3 A.H., with Asma Bint Umais present. Despite the Prophet's instruction against wrapping the baby in yellow cloth, it happened unintentionally. Upon return, the Prophet removed it, wrapped him in white, and named him Al-Hasan following divine revelation via Gabriel, adapting Haroun's son's name Shubbar to Arabic. He performed Adhan and Iqamah, and on the seventh day sacrificed rams, shaved the head, gave charity, and rejected the blood custom.","type":"Wiladat"},
  {"hijriMonth":9,"hijriDay":15,"title":"Departure of Muslim bin Aqil to Kufa","description":"Al Husayn dispatches Muslim Ibn Aqil to Kufa to assess support, facing journey perils where guides die of thirst; Muslim expresses doubt but continues after Al Husayn's urging. In Kufa, 18,000 Shia pledge allegiance to Al Husayn via Muslim. Governor al-Numan warns against rebellion. Reports reach Yazid, who appoints Ubayd Allah Ibn Ziyad as governor. Ubayd Allah arrives veiled, mistaken for Al Husayn, and enters the palace despite resistance.","type":"Event"},
  {"hijriMonth":9,"hijriDay":17,"title":"Battle of Badr","description":"In early 624, Muhammad led 313 Muslims to intercept a Quraysh caravan at Badr, but faced a 1000-strong army instead. After consultations affirming support from Muhajirs and Ansar, they secured water sources strategically. The battle began with duels where Ali and Hamza killed key Makkan champions, including Walid and Utbah. Muslims held firm against charges, counterattacked, slaying Abu Jahl and routing the enemy. Islam's first victory, with Ali killing 22, secured its survival; 50 prisoners were ransomed or freed after teaching literacy.","type":"Event"},
  {"hijriMonth":9,"hijriDay":19,"title":"Wounding of Imam Ali (as)","description":"Imam Ali foresaw his assassination by Abd Al-Rahman ibn Muljim, interacting with him multiple times and warning of treachery. Ibn Muljim, influenced by Qatam whose family Ali had killed, agreed to kill him for marriage, recruiting Shabib and Wirdan. On the 19th of Ramadan, Ali spent the night in prayer and shared prophetic dreams with his family. During dawn prayer at the mosque, Ibn Muljim struck him with a poisoned sword. Ali instructed kind treatment of his assassin, emphasizing mercy.","type":"Event"},
  {"hijriMonth":9,"hijriDay":20,"title":"Fath-e-Makkah (Conquest of Mecca)","description":"","type":"Event"},
  {"hijriMonth":9,"hijriDay":21,"title":"Martyrdom of Imam Ali (as)","description":"A group of Khawarij plotted to assassinate Imam Ali during Hajj in Makkah, blaming him for Muslim bloodshed alongside Mu’awiyah and Amr ibn Al-As; Abd Al-Rahman ibn Muljim targeted Ali on the 19th of Ramadan at dawn prayer. Evidence suggests Umayyad involvement through funding, incitement, and spies like Al-Ash’ath. Ali foresaw his death, advised Ibn Muljim, and spent the night in worship. Struck by Ibn Muljim’s poisoned sword during prostration, Ali issued last wills emphasizing piety, justice, and mercy, appointing Al-Hasan successor before dying on the 21st night.","type":"Shahadat"},
  {"hijriMonth":9,"hijriDay":23,"title":"Laylat al-Qadr","description":"Laylatul Qadr, the Night of Power in Ramadan, is better than a thousand months, with good deeds equaling those over that period. It commemorates the Quran's revelation as guidance for mankind, along with other holy books. The night marks the arrival of final divine guidance for happiness in both worlds, celebrated through spiritual worship and prayers. Believers' fates for the coming year are decreed then, encouraging all-night vigils for blessings and forgiveness.","type":"Event"},

  // Shawwal (10)
  {"hijriMonth":10,"hijriDay":1,"title":"Eid al-Fitr","description":"Eid-ul-Fitr is a spiritual festival marking the end of Ramadan, where Muslims thank Allah for the strength to fast and obey commandments, rejoicing in completing this sacred task rather than its departure. True Islamic sentiment views Ramadan's end with sorrow, as reflected in Imam Zainul-Abedeen's invocation praising its blessings. The festival lifts fasting restrictions but warns against un-Islamic indulgences. It offers three blessings: gratitude to God, self-reflection on character, and obligatory charity to the needy. Special prayers promote universal brotherhood, contrasting religion's elevation of human qualities with materialism's degradation.","type":"Eid"},
  {"hijriMonth":10,"hijriDay":3,"title":"Battle of Khandaq","description":"The Battle of Khandaq occurred in Ramadan, fifth year of Hijrat, when expelled Bani Nuzayr incited Quraish and tribes to form a 10,000-strong confederation against the Prophet in Medina. On Salman's advice, Muslims (700) dug a trench from Uhud to Rayah, with the Prophet breaking a rock revealing conquest visions. Miracles included multiplied food at Jabir's. Bani Quraiza betrayed their treaty. Ali slew champion Amr bin Abde Wudd in duel. After 20+ days' siege, a divine wind scattered enemies, ensuring Muslim victory despite hypocrites' doubts.","type":"Event"},
  {"hijriMonth":10,"hijriDay":8,"title":"Demolition of Jannat-ul-Baqi (Yaum-e-Gham)","description":"","type":"Event"},
  {"hijriMonth":10,"hijriDay":25,"title":"Martyrdom of Imam Jafar as-Sadiq (as)","description":"Imam Ja’far Sadiq (a.s.), born in 83 A.H. in Medina to Imam Muhammad Baqir (a.s.), lived 65 years and was martyred in 148 A.H. Renowned for profound knowledge, piety, and worship, he trained thousands of students, including major jurists like Abu Hanifah and Malik Ibn Anas, disseminating Islamic sciences during relaxed political times. His Imamate, lasting 34 years, was affirmed by his father and companions. He emphasized halal sustenance, almsgiving to the poor, patience in calamity, and ethical virtues, earning universal praise.","type":"Shahadat"},

  // Dhu al-Qi'dah (11)
  {"hijriMonth":11,"hijriDay":1,"title":"Wiladat Of Fatima al-Masuma (as), daugther of Imam Musa al-Kadhim (as)","description":"Lady Fatima Masuma (A), daughter of Imam Mūsā al-Kāđim (A) and Najmah Khātūn, was born on 1st Dhul Qa`dah 173 A.H. in Madina and died in Qum in 201 A.H. at age 28. Imams foretold her birth and burial in Qum over 45 years prior, promising paradise for her visitors and her intercession for Shi'a on Judgment Day. Known as Masuma and Karīmat Ahl al-Bayt, she narrated authentic traditions and remained unmarried due to lack of suitable matches amid persecution. Under her brother Imam al-Ridā's (A) guardianship, she achieved high spiritual knowledge.","type":"Wiladat"},
  {"hijriMonth":11,"hijriDay":9,"title":"Sending of a message from Muslim ibn Aqil (as) to Imam al-Hussain (as) regarding the situation in Kufa","description":"Muslim ibn Aqil sent a message to Imam al-Hussain warning him not to come to Kufa, as people will betray him.","type":"Event"},
  {"hijriMonth":11,"hijriDay":11,"title":"Wiladat Of Imam al-Ridha (as)","description":"Imam Ali al-Ridha, the Eighth Imam, was born in Medina in 148 Hijri and succeeded his father Imam Musa al-Kazim at age 35 after the latter's imprisonment and death by Harun al-Rashid. Facing Abbasid tyranny, he continued guiding followers discreetly. Summoned by Mamun to Merv in 200 Hijri amid succession struggles, he was appointed heir-apparent to gain Persian support, leading to Mamun's victory over Amin. Imam Ridha lived simply, established Karbala Majalis in Qom and Tus, and died poisoned in Tus in 203 Hijri at age 55, buried near Harun's tomb.","type":"Wiladat"},
  {"hijriMonth":11,"hijriDay":23,"title":"Martyrdom Of Imam Ali Raza (AS) (some traditions)","description":"","type":"Shahadat"},
  {"hijriMonth":11,"hijriDay":25,"title":"Dahwul Arz (The day the earth was spread)","description":"","type":"Event"},
  {"hijriMonth":11,"hijriDay":29,"title":"Martyrdom of Imam Muhammad al-Jawad (as)","description":"Imam Muhammad Taqi (Jawad), the Ninth Imam, was born in 195 A.H. in Medina to Imam Ridha and Sabikah. At age seven, he assumed Imamate after his father's martyrdom, lasting 17 years until his own at 25 in Baghdad under Mu’tasam. Narrations from Imam Ridha and companions confirm his succession, emphasizing his young age like Prophet Jesus. Despite short life, his knowledge, piety, and virtues shone in debates, such as with Yahya Ibn Aktham, and acts of worship and generosity.","type":"Shahadat"},

  // Dhu al-Hijjah (12)
  {"hijriMonth":12,"hijriDay":1,"title":"Marriage of Imam Ali ibn Abi Talib (as) to Fatima al-Zahra (as)","description":"After the Battle of Badr in 2 AH, Fatima Zahra, daughter of Prophet Muhammad, married Ali ibn Abi Talib, selected by Allah. Raised by her father after Khadija's death, Fatima embodied ideal womanhood through devotion and purity. Muhammad rejected other proposals, accepted Ali's, and conducted the wedding with a banquet and sermon. The procession to Ali's home featured recitations and prayers. Their marriage was harmonious, focused on service to God; Fatima raised four children while performing household duties and teaching Quran. In 2 AH, Eid prayers became sunnat.","type":"Event"},
  {"hijriMonth":12,"hijriDay":4,"title":"Imprisonment of Imam Musa al-Khadim (as)","description":"Harun al-Rashid imprisoned Imam Musa al-Kazim due to several reasons: the Imam's high personality and recognition as the rightful Imam by Muslims, evoking Harun's envy and malice; his craving for power, fearing the Imam's superiority; inherited hatred toward Alawids; informers accusing the Imam of collecting money and seeking caliphate; the Imam's demonstrations of his closer relation to Prophet Muhammad; specifying vast borders for Fedek; and the Imam's firm, non-flattering attitude toward Harun.","type":"Event"},
  {"hijriMonth":12,"hijriDay":7,"title":"Martyrdom of Imam Muhammad al-Baqir (as)","description":"Imam Muhammad al-Baqir, the fifth Shia Imam, born in 676 CE in Medina, succeeded his father Imam Zayn al-Abidin in 714 CE and led for 19 years until his poisoning in 733 CE at age 57. Known as Baqir al-Ulum for unveiling knowledge, he founded a school disseminating true Islamic teachings amid Umayyad oppression, trained disciples, emphasized Imamate and Wilayat, and exhibited piety, charity, and moral conduct. His legacy includes compiling jurisprudence and guiding against tyranny, with seven children including Imam Ja'far al-Sadiq. His sayings highlight Islam's pillars including Wilayat, the value of supplication, and scholarly humility.","type":"Shahadat"},
  {"hijriMonth":12,"hijriDay":8,"title":"Departure of Imam al-Hussain (as) from Makkah to Kufa","description":"Imam Hussein departs Makkah against warnings from his uncle Ibn Abbas and brother Mohammad-e-Hanafiya, leaving a letter declaring his intent to revive the Ummah's adherence to Amr-bil-Marouf and the path of his grandfather and father Ali. His journey to Kufa includes 14 stops: meetings with supporters like Zohair, dissuasion attempts, news of Muslim's death reducing followers to 50, a sermon at Baiza on tyranny, and aiding Hurr's thirsty army. Bypassing Kufa, he reaches Karbala on 2nd Muharram 61 Hijri, foreseeing martyrdom.","type":"Event"},
  {"hijriMonth":12,"hijriDay":9,"title":"Day of Arafah","description":"The Hajj pilgrimage requires traveling from Mecca to Arafat (knowledge) to remain until sunset on the ninth day, then briefly stopping at Mashar (consciousness) and staying in Mina (love and faith) from the tenth to twelfth or thirteenth day. These stages symbolize man's creation, descent from paradise after rebellion influenced by Satan and Eve, acquisition of wisdom and responsibility, repentance, and an eternal, restless movement toward Allah as direction, not destination, approaching absolute perfection through knowledge, consciousness, and love.","type":"Event"},
  {"hijriMonth":12,"hijriDay":9,"title":"Martyrdom Of Muslim ibn Aqil (as)","description":"Muslim Ibn Aqil fought bravely against his captors in Kufa but was weakened by stones and blows, including one that damaged his mouth. Promised security by Muhammad Ibn al-Ashath, he was betrayed and taken to Ubayd Allah Ibn Ziyad, who executed him by beheading from the palace top on 9th Dhu al-Hijja 60 A.H. He wept for al-Husayn's impending danger and made a will. Hani' Ibn Urwa was also killed in the marketplace. Their heads were sent to Yazid, who praised Ibn Ziyad's actions.","type":"Shahadat"},
  {"hijriMonth":12,"hijriDay":10,"title":"Eid al-Adha","description":"Eid al-Aḍḥā, celebrated on Dhu l-Hijja 10, commemorates Prophet Ibrahim's near-sacrifice of Isma'il, replaced by a ram from Jabra'il. Muslims perform sacrifices in Mina during Hajj as remembrance. Emphasis is on worship: vigil on the eve, ghusl, Eid Prayer, sacrifice, ziyarah of Imam al-Husayn, and al-Nudba Supplication. Fasting is forbidden, and it is an official holiday in Muslim countries with public ceremonies.The story details Ibrahim's submission, where the knife wouldn't cut, leading to God's acceptance and the ram's sacrifice. Imam Ali recommended vigils on this night.","type":"Eid"},
  {"hijriMonth":12,"hijriDay":15,"title":"Wiladat: Imam Ali Naqi (AS)","description":"","type":"Wiladat"},
  {"hijriMonth":12,"hijriDay":18,"title":"Eid al-Ghadir","description":"The transcript discusses Eid al-Ghadeer, emphasizing the Prophet Muhammad's appointment of Ali ibn Abi Talib as successor at Ghadir Khumm on 18 Dhul Hijjah, supported by Quranic verses (5:67 and 5:3) and hadiths like Hadith al-Ghadeer. It highlights the event's significance as completing Islam, with the Prophet declaring, 'Whomever I am his master, Ali is his master,' followed by pledges of allegiance. Historical sources from scholars like al-Tabari confirm it, refuting distortions of 'maula' as mere friend or cousin. The next episode will address Muslim disobedience to the Prophet.","type":"Eid"},
  {"hijriMonth":12,"hijriDay":22,"title":"Martyrdom of Maytham al-Tamar","description":"Meytham at Tammar, trained in esoteric knowledge by Imam Ali, was hanged and speared by Ubaydullah bin Ziyad, fulfilling prophecies. Rushayd al Hajari endured predicted torture and crucifixion by Ziyad. Hujr bin Adi opposed cursing Ali, leading to his arrest and execution by Mu’awiyah. ‘Amr bin Humaq, a devoted companion, was killed in Mosul. The infant sons of Muslim bin Aqeel escaped prison but were betrayed and beheaded.","type":"Shahadat"},
  {"hijriMonth":12,"hijriDay":24,"title":"Eid-e-Mubahila","description":"","type":"Eid"},
  {"hijriMonth":12,"hijriDay":25,"title":"Revelation of Surah Hal Ata (Al-Insan)","description":"","type":"Event"},
];
